### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by bronc** [fernadosilva/orvfms#10]
How can I select the proper timezone for my location? It syncs with the server but it looks like the server one is wrong.

**Comment by fernadosilva** [comment]
> On 23 May 2016, at 12:24, bronc notifications@github.com wrote:
> 
> How can I select the proper timezone for my location? It syncs with the server but it looks like the server one is wrong.
> 
> Hello,

Yes, it can happen because pgp uses or is configured to use a timeline different from your local one. Solution: 
1. Locate the file php.ini in your configuration; 
2. Google "php.ini timezone" 

Check the proper timezone line of your php.ini and replace it with the one of the supported php supported time zones that fit your location. To check the list of php supported time zones, just google it

Hope this helps, but please let me know if it solved your issue.

Rgds,

Fernando

**Comment by bronc** [comment]
Thanks Fernando, that worked.
