### ISSUE TITLE
IFTTT Support

### ISSUE THREAD

**Issue by billyabong** [fernadosilva/orvfms#16]
Not so much an issue but would love some advice/help on getting this working.

I've successfully installed your web interface and can control my wifi plugs but I'm having difficulty working out the right command for IFTTT to use to interact with it.  What I'm currently trying to get to work is using IFTTT to make a web request against "remoteIP/s20/index.php" pushing a particular button.  I've set the method to POST (can select from get, post, put, head, delete, patch, option) set content type to text/plain, and put the switch id into the body.  I can see you're using a form and button via submit and post but I can't for the life of me figure out an elegant way for me to get this to work.  

Any suggests would be greatly appreciated!

P.S I have tested remote access etc and all works as expected.

**Comment by javaftper** [comment]
Just out of interest, do you want to do this so you can control your plugs with Amazon Alexa? 

Or is it more along the lines of accessing the plugs when not connected to the wifi router? Or another use case?

As you probably know there are other github libraries that offer the Alexa angle that I have used although they are not PHP.  The two I am thinking of are-

https://github.com/makermusings/fauxmo (Java Alexa bridge that runs constantly listening for Alexa commands).

https://github.com/glenpp/OrviboS20 (python command line control- can be fired by fauxmo).

**Comment by billyabong** [comment]
Dang, thanks for the quick response, you nailed it on the head.  I'm actually trying to use my Google Home to control it and know someone who uses your github library so I figured I'd be able to get it to work.  

Would you suggest I use a different library than yours to get this to work?

I'm just trying to make a post via url to the php form which I figured would be pretty easy but doesn't seem to be.

**Comment by javaftper** [comment]
It's not my library but I do use it daily and try to contribute when I can.

I run orvfms on a raspberry Pi so it is available to all my devices on my network & only needs installing/maintaining in one place. I also have the other 2 libraries mentioned above installed so that I can use my Alexa although I don't actually use it that often.

I haven't seen any Google home type bridges although I don't have one so haven't looked at any of their libraries intentionally.

I guess if there is a library it will not be as comprehensive as fauxmo because the Alexa has been around a lot longer. But someone might do one at some point.

I'm unsure whether the proposed solution using a POST http call will be reliable. It definitely won't be as quick as the python and Java bridge which can also easily return the status of the switch.

**Comment by billyabong** [comment]
Oh lol, I just assumed.  My bad.

You're right that's the best solution to the problem.  I will look into that as a long term solution.  Just picked up my Google Home and wanted to play around with it.  Thanks for your help!

For anyone interested I ended up creating a unique php page for off/on for each device within the lib folder.  IFTTT sends a post command to the url and boom it turns on.
Here's my code:
`<?php

include("orvfms.php");

$s20Table = initS20Data(); 
$mac = "MAC ADDRESS";
$st = checkStatus($mac,$s20Table);

actionAndCheck($mac,(1),$s20Table);

?>`

**Comment by fernadosilva** [comment]
Hello,

Glad that you and javaftper solved the issue. I am in holidays and with limited connectivity!

Rgds,
