### ISSUE TITLE
server time sync, first socket setup and Scene from original app Wiwo

### ISSUE THREAD

**Issue by gkuhg** [fernadosilva/orvfms#8]
Hi,

I would kindly asking you to share your experiance on the following toipics:

**1.** Is it possible to connect/pair a virgin device to the local Wifi with the current implementation or the initial setup must be done via Wiwo app?
**2.** Is there any way to force time synchronization between s20 and server? I have observed that if I set a different server time it is not synchronised automatically and even there is no notification that socket ans server are running with different times.
**3.** Is there any posisbilities to group several devices and implement so called Scene like in original Wiwo app where with a single click you can "on" or "off" several sockets?

Thanks in advance for your answers and advises.

Regards,
George

**Comment by fernadosilva** [comment]
> On 20 Apr 2016, at 07:45, gkuhg notifications@github.com wrote:
> 
> Hi,
> 
> I would kindly asking you to share your experiance on the following toipics:
> 1. Is it possible to connect/pair a virgin device to the local Wifi with the current implementation or the initial setup must be done via Wiwo app?
> 
> No. At least so far, pairing must be done using the WiWo. I did not see any clear reason to fully replace the WiWo. It does a good job at this stage, it is an operation that has always to be performed locally, and I believe that everybody that buys an S20 has an Android or iPhone with WiWo.
> 2. Is there any way to force time synchronization between s20 and server? I have observed that if I set a different server time it is not synchronised automatically and even there is no notification that socket ans server are running with different times.
> 
> You are right. But recently (about two weeks ago) I published an update that checks  the synchronisation of timezone (TZ) and DST between the socket and the server. This followed a couple of requests that were reinforced by the recent Winter to Summer time change (or vice-versa) in Europe and other regions. If socket and server are in different TZ or DST modes, a warning yellow icon/button appears on the main page which provides access to setup page, where now a sync button is available. 

Note that this sync option only provides TZ/DST synchronization, since the socket UTC universal timer seems always  be synchronised by some external service. It is easy to add this UTC timer synchronisation, if it is required and there is a good case for it, but so far I did not see any good reason to implement it. Note that sometime socket and server times are 1 or even 2 seconds out of phase, but that is may be due to software delay or different sync services,  and they are not easy (nor worth) to correct.

> 1. Is there any posisbilities to group several devices and implement so called Scene like in original Wiwo app where with a single click you can "on" or "off" several sockets?
> 
> Sure, it is quite easy to implement. I have no immediate plans for it, but I can think about it. I would have to find a smooth way of integrate that option in the main page interface. Please let me know if you have any suggestions.

Regards,

— Fernando

**Comment by gkuhg** [comment]
Thanks Fernando,

I got your point :).
Concerning Scene feature I will think and come with proposal.

Regards,
George

**Comment by gkuhg** [comment]
Hello Fernando,

Do you think it is possible to have additional icon near to search one for a "Scene" feature where the scene will be defined?

![scene](https://cloud.githubusercontent.com/assets/18518664/14743266/0c0b61e6-08a1-11e6-8a80-7ecf01d05c9a.png)

Best regards,
George

**Comment by fernadosilva** [comment]
Hello,

Thanks for the suggestion. Yes, that is the most obvious solution. But I can not commit right now with a specific timing to include that functionality. But I will try to advance a little bit.

Rgds,

— fernando

**Comment by gkuhg** [comment]
Thanks,
George

**Comment by fernadosilva** [comment]
Hello,

I just published an updated version of orvfms  with a prototype version of the scene feature. Please let me know if it 
fits your needs.  You can also also help me on debug processing and checking if it works as expected. I will have to 
improve the interface, but I believe that os already “workable”.

Please check in globals.php the new TMP_DIR variable and adjust it to your system. Otherwise, scene configuration data will be 
stored on the system temporary directory, which may be erased during maintenance or reboot procedures.

Regards,

Fernando

**Comment by gkuhg** [comment]
Thank you so much, I am going to check it and let you know in the next 1-2 days.
Take care,
George

**Comment by gkuhg** [comment]
I have tried and get the following "Warning" before I created the first Scene which creates as well the scene_orvfms.dat file. The rest works perfect :) .
![bildschirmfoto 2016-04-28 um 20 47 16](https://cloud.githubusercontent.com/assets/18518664/14897544/af1ea22c-0d82-11e6-8328-6c26d6490565.png)

**Comment by chrisbyrneham** [comment]
These sockets stopped working properly for me last year, due to the synch issue, this might help https://github.com/chrisbyrneham/S20-Life-Extender it's a little Arduino ESP8266 sketch that will synchronise the time on the old S20 sockets, now that the Orvibo time server for them seems to have been decommissioned around mid 2019.
You can still use the Wiwo app to program them.

**Comment by javaftper** [comment]
Did you re-clone/update your local code with this commit from Fernando?
https://github.com/fernadosilva/orvfms/commit/5d780d8ce9a36d7217ffb310af07c1b55f888014
It was on 4 October last year.
It removed the dependency on the orvibo NTP server- now utilising the web server datetime.
I've been using it since then and it provides all the date/timer functions etc.
What isn't working for you?

**Comment by chrisbyrneham** [comment]
Thanks for your comment, I think I've got the latest update. Orvfms is a great app, and I appreciate it and use it a lot. (Thanks Fernando!) It's just that it needs to be running on a webserver and php and has to have a browser on the page continuously to do the refresh, and then you manually update the switches if they go out of synch. My idea was to have a dead simple ESP8266 that you could plug in and would keep the switches synchronised. When you need to monitor or change the switch timer programming then I run up Orvfms, or the Wiwo app ( I bet that becomes unavailable soon too ).

**Comment by sultanoswing** [comment]
"has to have a browser on the page continuously to do the refresh, and then
you manually update the switches if they go out of synch"

I'm fortunate that I do have a webserver on all the time, but it would be
fantastic if an automated timesync function could be built in to the orvfms
code, as was suggested late last year i.e. the socket checks and syncs with
server time every 24hrs.

Although not an arduous task to manually hit the 'sync' button when the
warning sign shows, got to love full automation, right?
