### ISSUE TITLE
Unable to add new timer to plug

### ISSUE THREAD

**Issue by Adam1986** [fernadosilva/orvfms#9]
Hello,

I am struggling to add a new timer schedule to my sockets.

When I click to add a new schedule I receive the following error:

Notice: Undefined offset: -1 in edit_page.php on line 59

If I proceed to add the schedule as normal, nothing is saved unfortunately - is there any advise on fixing this?

This is running on Windows Apache with PHP.

Cheers

**Comment by fernadosilva** [comment]
Hello Adam,

Thank you for your report. This problem was never reported before, but it should not happen. I have to check the code and try to understand a possible source of the problem, but it is certainly something quite simple. Give me 24/48 hours, since I am a little busy with other stuff right now. 

Rgds,

Fernando

**Comment by Adam1986** [comment]
Hi Fernando,

Thanks for responding so quickly.  I appreciate this.

I also get the following error if I go into configure socket.:

Notice: Undefined index: next in setup_page.php on line 36

If I get a chance I will spin up a Ubuntu VM and test inside that.

Cheers

**Comment by fernadosilva** [comment]
Hello Adam,

Sorry for the delay, but I've been to busy and only now I had the time to look at this. A little bit more than the 48 hours I promised :-(.

As I anticipated, the first error you reported it was a quite simple bug of mine. I did not detected it because it was being processed gently (ignored) by my php interpreter -- possibly the same happened to other users of the code that never detected it. But it is corrected in the version I just uploaded to  github, can you please download and test it again? Thank you for your report!

Regarding the second one  "Undefined index: next in setup_page.php on line 36", and I was not able to detect a possible source, but it may result of a inconsistent state as a consequence of the previous bug. Please try the following: close your browser (to clear session cookies and data) and remove the file orvfms.dat that should be present in your temporary dir, and try again.

Hope this helps.

Rgds,

-- Fernando

**Comment by Adam1986** [comment]
Hello Fernando,

Sorry for the delay in replying I've been pretty busy too.

I've just downloaded the latest version and have applied it onto the web server.  Everything is working as it should now so many thanks for looking into this for me.

The undefined index now also appears to have cleared out so now I am fully up and running.

Thanks :-)

**Comment by fernadosilva** [comment]
Great. Thank you for your cooperation and report.

Reds,
